name: my_test_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  http: ^1.2.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4

  # Tables & UI
  data_table_2: ^2.5.9
  font_awesome_flutter: ^10.7.0
  intl: ^0.20.2
  fl_chart: ^0.68.0

  # Ù…ÙƒØªØ¨Ø§Øª Ø§Ù„Ø·Ø¨Ø§Ø¹Ø© ÙˆØ§Ù„Ø¥ÙŠØµØ§Ù„Ø§Øª
  pdf: ^3.11.3
  printing: ^5.11.1
  open_filex: ^4.3.2

  # Export to Excel
  excel: ^4.0.6
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  universal_html: ^2.2.0

  # Extra packages
  provider: ^6.1.2
  geolocator: ^14.0.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3

  # ðŸ‘‡ðŸ» Ù…ÙƒØªØ¨Ø§Øª Material 3 Dynamic Design ÙˆØ§Ù„Ø£ÙŠÙ‚ÙˆÙ†Ø§Øª
  dynamic_color: ^1.8.1 # Ù„ØªØ·Ø¨ÙŠÙ‚ Ø§Ù„Ø£Ù„ÙˆØ§Ù† Ø§Ù„Ø¯ÙŠÙ†Ø§Ù…ÙŠÙƒÙŠØ© Material You
  material_design_icons_flutter: ^7.0.7296 # Ù„ØªÙˆÙÙŠØ± Ø¢Ù„Ø§Ù Ø§Ù„Ø£ÙŠÙ‚ÙˆÙ†Ø§Øª Ø§Ù„Ø¥Ø¶Ø§ÙÙŠØ©
  # ðŸ’¡ ØªÙ… ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ø¥ØµØ¯Ø§Ø± Ø¥Ù„Ù‰ Ø§Ù„Ø¥ØµØ¯Ø§Ø± Ø§Ù„Ù…Ù‚ØªØ±Ø­
  lucide_icons: ^0.257.0

  # Ø­Ø²Ù… Ø§Ù„ØµÙˆØ± ÙˆØ§Ù„Ø´Ø¨ÙƒØ©
  cached_network_image: ^3.3.1

  # Ù…ÙƒØªØ¨Ø§Øª Ø§Ù„Ø®Ø±Ø§Ø¦Ø· (Ù…ØªØ¹Ø¯Ø¯Ø© Ø§Ù„Ù…Ù†ØµØ§Øª)
  flutter_map: ^5.0.0
  latlong2: ^0.9.1
  # Ø§Ù„Ø¥ØµØ¯Ø§Ø± Ø§Ù„Ù…Ø³ØªÙ‚Ø± Ø§Ù„Ø°ÙŠ ÙŠØ¯Ø¹Ù… Null Safety Ù„ØªØ­Ù„ÙŠÙ„ GeoJSON
  flutter_map_geojson: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/OSMB-bc319d822a17aa9ad1089fc05e7d4e752460f877.geojson
